### ISSUE TITLE
Implement the left-swimming turbofish

### ISSUE THREAD

**Issue by chris-morgan** [jplatte/turbo.fish#10]
On https://www.reddit.com/r/rust/comments/cpknjb/i_just_found_out_that_method_is_valid/, fully-qualified syntax is discussed, so that you can have `<_>::` instead of `::<_>`. /u/ekuber then remarked:

> You've found the left-swimming turbofish!

Yeah, I think turbo.fish should implement the left-swimming turbofish!

**Comment by chris-morgan** [comment]
I’m now imagining a ridiculous expression like `<_>::v::<_>(0)`.

**Comment by estebank** [comment]
`<_>::v::<_>(v) ^ <_>::v::<_>(v)`

**Comment by jplatte** [comment]
Done!
