### ISSUE TITLE
Earlier use of Turbofish found

### ISSUE THREAD

**Issue by nuew** [jplatte/turbo.fish#14]
Apparently the reddit post is not the first use of the term turbofish, beaten by less than a day [via twitter](https://twitter.com/garblefart/status/627886036211900416). See @steveklabnik's new [historical note](https://github.com/steveklabnik/rust/commit/4f22b4d1dbaa14da92be77434d9c94035f24ca5d#r35123951).

The README should be updated to account for this.

**Comment by jplatte** [comment]
Actually it looks like that twitter post was written very shortly *after* the reddit comment. reddit says `Sun Aug 02 2015 18:57:00 GMT+0200`. GMT+0200 / Central European Summer Timer is my timezone, and when I view that tweet logged-in (which seems to be required for it to not show timestamps in some completely different timezone) it tells me it's from within that same minute on that day - no second is shown.

**Comment by jplatte** [comment]
It hardly matters, given it's the same person.
