### ISSUE TITLE
left swimming turbofish using emojis doesn't work

### ISSUE THREAD

**Issue by lcnr** [jplatte/turbo.fish#17]
I tried the following which works as expected.
https://turbo.fish/::%3C%F0%9F%A5%BA%F0%9F%91%89%F0%9F%91%88%3E

trying the reverse, either by clicking `reverse!` or by manually modifying the url does not work however <https://turbo.fish/%3C%F0%9F%A5%BA%F0%9F%91%89%F0%9F%91%88%3E::>

It instead just shows a black screen.

Browser: Mozilla Firefox 88.0 (64-bit) on Ubuntu

🥺👉👈

**Comment by jplatte** [comment]
Produces an internal server error. Will look into it.

**Comment by jplatte** [comment]
I was using `str::split_at` like a fool! Rewritten to use `strip_prefix` & `strip_suffix`.

**Comment by jplatte** [comment]
I'll close this issue once the fix is deployed. I'm curious though: How did you discover this? 😄

**Comment by lcnr** [comment]
i've seen it used as an attempt to flirt with http://turbo.fish/ and hit `reverse!` because I was able to do so
