### ISSUE TITLE
Add dedication to Anna Harren

### ISSUE THREAD

**Issue by HollayHorvath** [jplatte/turbo.fish#18]
[Rust release 1.55](https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html) is dedicated to Anna Harren who coined the "turbofish" term. She recently passed away. I think adding a link to this specific release would be a kind way of remembering.

**Comment by jplatte** [comment]
There's not really a good place to put this right now, I've been meaning to add an about page but this "project" is not really high on my list of priorities. If you're interested in doing the work of adding that page, I'd be happy to review / help out / write up rough instructions.
