### ISSUE TITLE
Reddit user deadstone was my daughter Anna

### ISSUE THREAD

**Issue by Anke00** [jplatte/turbo.fish#26]
Hello, I have a huge request.

I noticed that a Google search on why the turbofish is called that points here. I am the mum of Anna whose reddit username was deadstone. 

My daughter Anna sadly passed away in 2021. She had leukaemia and it was all completely horrible. Steve dedicated the next version of Rust to her memory. https://twitter.com/rustlang/status/1435973155970027526

Can we make this paragraph into another little shrine to her memory? So it doesn't just say "reddit user deadstone"? 

That would be so lovely. 

Thank you <3

**Comment by jplatte** [comment]
Hi! I think you are referring to the README.md file?

![Screenshot_2023-01-25_141717](https://user-images.githubusercontent.com/951129/214573279-592f59f4-196a-4336-a3d2-3e2d2c105bdb.png)

If so, how do you feel about me just using the same text for the readme as what was recently added to the website itself at https://turbo.fish/about?

**Comment by Anke00** [comment]
Hi Jonas, yes that would be lovely

Thank you
________________________________

**Comment by jplatte** [comment]
I've updated the readme. I'm going to mark this as done, but feel free to leave further comments.
