### ISSUE TITLE
Q: Is there a real species that the turbofish operator is named after?

### ISSUE THREAD

**Issue by pavpen** [jplatte/turbo.fish#29]
It may seem like a basic question, but I was expecting turbofish to be a real species, and can't figure out which one that may be. If you do know what is its scientific name? Perhaps, you can add an answer to this question to the Web site.

I know there's turbot (Scophthalmus maximus) with the extra 't'. It does resemble the 'ASCII art' of the operator, but that may be true for quite a few species.

**Comment by jplatte** [comment]
I highly doubt that there is one. All I know about the history is what's in the readme file / on the about page of the website.
